apiVersion: kpack.io/v1alpha2
kind: ClusterBuildpack
metadata:
  name: cds-java
spec:
  serviceAccountRef:
    name: dependencies-pull-serviceaccount
    namespace: build-service
  image: anthonydahanne/java:cds-april-4
