apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search-cds
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: where-for-dinner-search
    networking.knative.dev/visibility: cluster-local
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: clusterBuilder
    value: cds      
  - name: api_descriptor
    value:
      type: openapi
      location: 
        path: "/v3/api-docs"
      owner: where-for-dinner-team
      system: where-for-dinner
      description: Where For Dinner Search API              
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"     
      - name: BP_JVM_CDS_ENABLED
        value: true         
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: msgbroker-where-for-dinner
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
    subPath: where-for-dinner-search