apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search-proc
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: where-for-dinner-search-proc
    networking.knative.dev/visibility: cluster-local
spec:
  env:
  - name: spring_profiles_active
    value: crawler,rabbitmq
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"        
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"  
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: msgbroker-where-for-dinner
  source:
    git:
      url: https://github.com/gm2552/wfd-cds-preview
      ref:
        branch: main
    subPath: workloads/where-for-dinner-search-proc