apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-availability-mariadb2training
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: where-for-dinner-availability
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: clusterBuilder
    value: cds                  
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"   
      - name: BP_JVM_CDS_ENABLED
        value: "true"
      - name: CDS_TRAINING_JAVA_TOOL_OPTIONS
        value: "-Dspring.profiles.active=training-run"  
  env:
  - name: spring_profiles_active
    value: mysql,rabbitmq     
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: msgbroker-where-for-dinner 
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: db-where-for-dinner  
  source:
    git:
      url: https://github.com/gm2552/wfd-cds-preview
      ref:
        branch: main
    subPath: workloads/where-for-dinner-availability